spring.profiles.active: local

# face-api settings
face-api:
  key: REPLACE_TO_YOURS

# cloudinaly settings
cloudinaly:
  cloudName: REPLACE_TO_YOURS
  apiKey: REPLACE_TO_YOURS
  apiSecret: REPLACE_TO_YOURS
  overlayImagePixelLimit: 640
  meterPixelSize: 200
  previewMeterPixelSize: 60