# spring settings
server:
  port: 9090

# DB
spring.datasource.url: ${JDBC_DATABASE_URL}
spring.datasource.username: ${JDBC_DATABASE_USERNAME}
spring.datasource.password: ${JDBC_DATABASE_PASSWORD}
spring.datasource.driverClassName: org.postgresql.Driver
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true
