# spring settings
server:
  port: 8080

# face-api settings
face-api:
  key: REPLACE_TO_YOURS

# cloudinaly settings
cloudinaly:
  cloudName: REPLACE_TO_YOURS
  apiKey: REPLACE_TO_YOURS
  apiSecret: REPLACE_TO_YOURS
  meterPixelSize: 150

